objstoreConfig: |-
  type: s3
  config:
    bucket: test-automation-thanos
    endpoint: s3.us-east-1.amazonaws.com
    access_key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    secret_key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    insecure: true  
querier:
  stores:
    - XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:YYYYY
    - XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:YYYYY
    - XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:YYYYY
bucketweb:
  enabled: false
compactor:
  enabled: true
  persistence:
    enabled: false
storegateway:
  enabled: true
  persistence:
    enabled: false
ruler:
  enabled: true
  persistence:
    enabled: false
  alertmanagers:
    - http://prometheus-operator-alertmanager.prometheus-thanos.svc.cluster.local:9093
  config: |-
    groups:
      - name: "metamonitoring"
        rules:
          - alert: "PrometheusDown"
            expr: absent(up{prometheus="prometheus-thanos/prometheus-operator"})    
